### ISSUE TITLE
Issue with Frigate script

### ISSUE THREAD

**Issue by mhoogenbosch** [remz1337/Proxmox#13]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

During deployment i get the following error

```
Loading the ONNX file...
Adding yolo_layer plugins.
Adding a concatenated output as "detections".
Naming the input tensort as "input".
Building the TensorRT engine.  This would take a while...
(Use "--verbose" or "-v" to enable verbose logging.)
Available tensorrt models:
ls: cannot access '*.trt': No such file or directory

[ERROR] in line 192: exit code 0: while executing command $STD bash /opt/frigate/docker/tensorrt/detector/rootfs/etc/s6-overlay/s6-rc.d/trt-model-prepare/run
root@z240:~# 
```

I can't log in because I don't know the password.

The system i'm using is a HP Z240 with a Nvidia P2000 gpu.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/fa37db35-eda1-47f3-9a59-293b4f15ec8a)

### Please provide detailed steps to reproduce the issue.

Execute bash -c "$(wget -qLO - https://github.com/remz1337/Proxmox/raw/remz/ct/frigate.sh)"

**Comment by remz1337** [comment]
from the host shell, simply run `pct enter <lxc id>` to log in. I'm suspecting a TensorRT issue due to mismatch in CUDA version. There was another issue related to this, where older GPU (such as yours) did not support the default CUDA version that comes with the latest drivers. Look in the logs if you see any error message about CUDA  or TensorRT.

Otherwise, log in and try to see if the trt files are somewhere else. You can also run the trt commands manually from the script and see where it blocks

**Comment by mhoogenbosch** [comment]
Cool! didn't know that command. Inside the LXC i have exactly the same output for nvidia-smi as on host. On a different host, cuda 12.4 is working, but with a RTX 3060 card.

There haven't been any *.trt files generated find / -name *trt doens't find anything.

I haven been looking at how to run the command manually. https://github.com/remz1337/Proxmox/blob/remz/install/frigate-install.sh is the file i guess is the one I need to check, but i'm stuck. Honestly wouldn't know what to run.

**Comment by remz1337** [comment]
Yes, I'm pretty sure that's the issue (older GPU). My setup uses Turing architecture Nvidia GPU (T600) and RTX 3060 uses Ampere architecture (more recent), but P6000 has Pascal architecture (older). The right fix would be to rework the script and allow a different CUDA version, but that's a lot of effort I'm not willing to invest. Plus, I could not even test it. But if you want to work on this, I'd be happy to accept a pull request.

As I have suggested previously here (issue https://github.com/remz1337/Proxmox/issues/8), there's potential workaround if you can find a recent driver version (>500) that comes with CUDA 11 instead of 12.

Now, if you want to debug manually, first run the script to create a base debian 11 lxc, then enter the LXC and copy paste each command from the `frigate-install` script one by one. For the debian LXC, run this from the host `bash -c "$(wget -qLO - https://github.com/remz1337/Proxmox/raw/remz/ct/debian.sh)"`, then you need to go into advanced and select debian 11 and also enable GPU passthrough.

**Comment by mhoogenbosch** [comment]
I tried this system to see if it would consume less power than my current system. But although it has less cpu, a less powerfull gpu and only one disk (compared to 3 in my current setup), it consumes just as much. 

So I just put it back to it's original owner. Thanks for your help, but i'll close the issue.
